[phases.setup]
nixpkgs = [
  "pkg-config",
  "cairo",
  "libpng",
  "pango",
  "giflib",
  "jpeg",
  "fontconfig",
  "freetype",
  "noto-fonts-emoji",
  "noto-fonts",
  "fontconfig"
]

[phases.install]
cmds = [
  "pnpm install",
  "fc-cache -fv",
  "fc-list | grep -i emoji || echo 'No emoji fonts found'",
  "fc-list | grep -i noto || echo 'No Noto fonts found'"
]

[phases.build]
cmds = [
  "pnpm rebuild canvas"
]

[start]
cmd = "pnpm start" 